version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8888:80
  web1:
    build: .
    depends_on:
      - nginx
    volumes:
      - /media/Docker/web1:/app/uploads
    environment:
      PORT: 8000
  web2:
    build: .
    depends_on:
      - nginx
    volumes:
      - /media/Docker/web2:/app/uploads
    environment:
      PORT: 8000
  web3:
    build: .
    depends_on:
      - nginx
    volumes:
      - /media/Docker/web3:/app/uploads
    environment:
      PORT: 8000
